resources: 
  - name: app
    type: GitRepo
    configuration: 
        gitProvider: Test
        path: pulak-kanti/Basic-CRUD-Flask-REST-api
        branches: 
            include: master

pipelines:
    - name: pipeline_hello_world
      configuration:
        environmentVariables:
          readOnly:
            MY_MESSAGE: '"Hello World!"'
      steps:
        - name: step_1
          type: Bash
          configuration:
            inputResources:
              - name: app
          execution:
            onExecute:
              - echo $MY_MESSAGE
              