resources: 
  - name: app
    type: GitRepo
    configuration: 
        gitProvider: Test
        path: pulak-kanti/Basic-CRUD-Flask-REST-api
        branches: 
            include: master

pipelines:
    - name: pipeline_hello_world
      configuration:
        environmentVariables:
          readOnly:
            MY_MESSAGE: '"Hello World!"'
      steps:
        - name: step_1
          type: Bash
          configuration:
            inputResources:
              - name: app
          execution:
            onExecute:
              - echo $MY_MESSAGE
        - name: step_2
          type: Bash
          configuration:
            inputResources:
              - name: app
          execution:
            onExecute:
              - sudo apt-get python3.6
              - git clone https://github.com/pulak-kanti/Basic-CRUD-Flask-REST-api.git
              - cd Basic-CRUD-Flask-REST-api
              - pip install -r requirements.txt
              - python -m pytest
              - echo "Step_2 Done"
              