resources: 
  - name: app
    type: GitRepo
    configuration: 
        gitProvider: Test
        path: pulak-kanti/Basic-CRUD-Flask-REST-api
        branches: 
            include: master
        buildOn:
          commit: true
          pullRequestCreate: true


pipelines:
    - name: pipeline_hello_world
      configuration:
        environmentVariables:
          readOnly:
            MY_MESSAGE: '"Hello World!"'
      steps:
        - name: step_1
          type: Bash
          configuration:
            inputResources:
              - name: app
          execution:
            onExecute:
              - echo $MY_MESSAGE
        - name: step_2
          type: Bash
          configuration:
            inputSteps:
              - name: step_1
          execution:
            onExecute:
              - ls
              - ll
              - cd /var/opt/jfrog/pipelines/data/pipeline_hello_world/runs
              - ls
              - cd /var/opt/jfrog/pipelines/data/pipeline_hello_world/workspace
              - ls
              - printenv
              - pip install -r requirements.txt
              - python -m pytest
              - echo "Step_2 Done"
        - name: step_3
          type: Bash
          configuration:
            inputSteps:
              - name: step_2
          execution:
            onExecute:
              - echo "Step_3 Done"
            
              